# Generated by Django 3.1.7 on 2021-07-19 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_auto_20210719_0504'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurants',
            options={'verbose_name_plural': 'Restaurants'},
        ),
        migrations.AddField(
            model_name='restaurants',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='name',
            field=models.CharField(max_length=100, verbose_name="Hotels's name"),
        ),
    ]
