# Generated by Django 3.1.7 on 2021-07-19 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_auto_20210719_0526'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Restaurants',
            new_name='Hotels',
        ),
    ]
